# Generated by Django 4.2 on 2024-11-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operator',
            name='last_alert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='notification_threshold',
            field=models.IntegerField(choices=[(1, 'After 1 alert'), (4, 'After 4 alerts'), (7, 'After 7 alerts')], default=1),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
