# Generated by Django 4.2 on 2024-11-05 15:41

import django.core.validators
from django.db import migrations, models

def move_settings(apps, schema_editor):
    OldSettings = apps.get_model('monitoring', 'SystemSettings')
    NewSettings = apps.get_model('settings', 'SystemSettings')
    
    try:
        old_settings = OldSettings.objects.first()
        if old_settings:
            NewSettings.objects.create(
                normal_temp_min=old_settings.normal_temp_min,
                normal_temp_max=old_settings.normal_temp_max,
                critical_temp_min=old_settings.critical_temp_min,
                critical_temp_max=old_settings.critical_temp_max,
                reading_interval=old_settings.reading_interval,
                alert_reset_time=old_settings.alert_reset_time,
                require_2fa=old_settings.require_2fa
            )
    except Exception:
        pass

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_temp_min', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('normal_temp_max', models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('critical_temp_min', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('critical_temp_max', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('reading_interval', models.IntegerField(choices=[(10, '10 minutes'), (20, '20 minutes'), (30, '30 minutes')], default=20, help_text='Reading interval in minutes')),
                ('alert_reset_time', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=30, help_text='Time before alert can be triggered again')),
                ('require_2fa', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.RunPython(move_settings),
    ]
