# Generated by Django 4.2 on 2024-11-11 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_temp_min', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('normal_temp_max', models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('critical_temp_min', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('critical_temp_max', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('reading_interval', models.IntegerField(choices=[(10, '10 minutes'), (20, '20 minutes'), (30, '30 minutes')], default=20, help_text='Reading interval in minutes')),
                ('alert_reset_time', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=30, help_text='Time before alert can be triggered again')),
                ('require_2fa', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
