# Generated by Django 4.2 on 2024-11-02 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('power_status', models.BooleanField(default=True)),
                ('battery_power', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_temp_min', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('normal_temp_max', models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('critical_temp_min', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('critical_temp_max', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)])),
                ('reading_interval', models.IntegerField(choices=[(10, '10 minutes'), (20, '20 minutes'), (30, '30 minutes')], default=20, help_text='Reading interval in minutes')),
                ('alert_reset_time', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=30, help_text='Time before alert can be triggered again')),
                ('require_2fa', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEMP_HIGH', 'Temperature Too High'), ('TEMP_LOW', 'Temperature Too Low'), ('POWER_OUT', 'Power Outage'), ('POWER_RESTORED', 'Power Restored')], max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.reading')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
