# Generated by Django 4.2 on 2024-11-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='device_id',
            field=models.CharField(default='default_device', help_text='Unique identifier for the monitoring device', max_length=100),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type', 'timestamp'], name='monitoring__type_ac03cf_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['device_id', 'timestamp'], name='monitoring__device__aa54d5_idx'),
        ),
    ]
