# Generated by Django 4.2 on 2024-11-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttimelineevent',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.operator'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='monitoring.incident'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.operator'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to='notifications.operator'),
        ),
        migrations.AddField(
            model_name='alert',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.reading'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'start_time'], name='monitoring__status_74828a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type', 'timestamp'], name='monitoring__type_ac03cf_idx'),
        ),
    ]
