# Generated by Django 4.2 on 2024-12-25 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('error', 'Error')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='reading_interval',
            field=models.IntegerField(default=300),
        ),
    ]
