# Generated by Django 4.2 on 2024-12-25 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_device_is_active_device_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reading',
            name='monitoring__device__aa54d5_idx',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='device',
        ),
        migrations.AddField(
            model_name='reading',
            name='device_id',
            field=models.CharField(default='ESP8266_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='reading',
            name='power_status',
            field=models.CharField(choices=[('AC', 'AC Power'), ('BATTERY', 'Battery Power')], default='AC', max_length=20),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['device_id', '-timestamp'], name='monitoring__device__6c85a9_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_e0b919_idx'),
        ),
    ]
