# Generated by Django 4.2 on 2025-01-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_remove_reading_monitoring__device__aa54d5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
