# Generated by Django 4.2 on 2025-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_reading_timestamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='monitoring__alert_t_3d4874_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitoring__device__fa620c_idx',
        ),
        migrations.AddField(
            model_name='alert',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('high_temperature', 'High Temperature'), ('low_temperature', 'Low Temperature'), ('power_failure', 'Power Failure'), ('low_battery', 'Low Battery'), ('connection_lost', 'Connection Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('severe', 'Severe'), ('warning', 'Warning')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-timestamp'], name='monitoring__device__d61f56_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_53f01c_idx'),
        ),
    ]
