# Generated by Django 4.2 on 2025-01-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_retry_count'),
        ('monitoring', '0007_alter_incident_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentcomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidentcomment',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.operator'),
        ),
    ]
